//76576500

public class Veloz12 {
    public static void main(String[]args) {
        System.out.println(firstWith500Divis(500));

    }

    public static long firstWith500Divis(int target) {
        long n = 1;

        while(true) {
            long triangle = n * (n + 1)/2;
            int divisors = countDivisForTriangles(n);

            if(divisors > target) { 
                return triangle;
            }

            n++;
        }
    }
        private static int countDivisForTriangles(long n) {
            long a = n;
            long b = n + 1;

            if(a % 2 == 0) a /= 2;
            else b /= 2;

            return countDivisors(a) * countDivisors(b);
        }

        private static int countDivisors (long num) {
            int count = 1;
            long factor = 2;

            while(factor * factor <= num) {
                int exp = 0;
                while (num % factor == 0) {
                    num /= factor;
                    exp++;
                }
                count*= (exp + 1);
                factor++;
            }
            if (num > 1) count *= 2;
            return count;

        }
    
    
}

//The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 +2 +3 +4 +5 +6 +7 =28. The first ten terms would be:
//1,3,6,10,15,21,28,36,45,55,…
//Let us list the factors of the first seven triangle numbers:
//𝟏	:1
//𝟑	:1,3
//𝟔	:1,2,3,6
//𝟏𝟎	:1,2,5,10
//𝟏𝟓	:1,3,5,15
//𝟐𝟏	:1,3,7,21
//𝟐𝟖	:1,2,4,7,14,28
//We can see that 28 is the first triangle number to have over five divisors.
//What is the value of the first triangle number to have over five hundred divisors?